# Generated by Django 3.0 on 2020-11-26 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_banner_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='active',
        ),
    ]
